version: '2'
services:
  api:
    image: ${DOCKER_IMAGE}${DOCKER_ENVIRONMENT}:${DOCKER_TAG}
    depends_on:
      - redis
      - minio
    volumes:
      - ./src:/go/src/github.com/${DOCKER_IMAGE}/src
    ports:
      - 8080:8080
    environment:
      DEBUG: "true"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASS: ""
      MINIO_HOST: "minio"
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: "minioclient"
      MINIO_SECRET_KEY: "supersecret"
      MINIO_PUBLIC_URL: "http://localhost:9000"

  redis:
    image: redis:3.2-alpine

  minio:
    image: minio/minio:RELEASE.2016-10-07T01-16-39Z
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "minioclient"
      MINIO_SECRET_KEY: "supersecret"